# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('active_users', models.IntegerField(default=0, verbose_name='actives')),
            ],
        ),
    ]
