# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_dau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dau',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
